apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: windfire-restaurants-node-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/robipozzi/windfire-restaurants-node
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: windfire-restaurants-node-image
spec:
  type: image
  params:
    - name: url
      value: docker.io/robipozzi/windfire-restaurants-node #configure: replace with where the image should go: perhaps your local registry or Dockerhub with a secret and configured service account
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/docker-source/Dockerfile
      - name: pathToContext
        type: string
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/docker-source
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.15.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.builtImage.url)
        - --context=$(inputs.params.pathToContext)
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-docker-image-from-git-source-task-run
spec:
  serviceAccountName: tekton-serviceaccount
  taskRef:
    name: build-docker-image-from-git-source
  inputs:
    resources:
      - name: docker-source
        resourceRef:
          name: windfire-restaurants-node-git
    params:
      - name: pathToDockerFile
        value: Dockerfile
      - name: pathToContext
        value: /workspace/docker-source/
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: windfire-restaurants-node-image