apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-serviceaccount
secrets:
  - name: dockerhub-secret
imagePullSecrets:
  - name: dockerhub-secret
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-imagebuilders
  annotations:
    openshift.io/description: >-
      Allows builds in this namespace to push images to this namespace.  It is
      auto-managed by a controller; remove subjects to disable.
subjects:
  - kind: ServiceAccount
    name: tekton-serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin