apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-push-image-taskrun
spec:
  serviceAccountName: tekton-serviceaccount
  taskRef:
    name: build-push-image
  inputs:
    resources:
      - name: git-source
        resourceRef:
          name: windfire-restaurants-node-git
    params:
      - name: pathToDockerFile
        value: Dockerfile
      - name: pathToContext
        value: /workspace/git-source
  outputs:
    resources:
      - name: image
        resourceRef:
          name: windfire-restaurants-node-image
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: deploy-image-taskrun
spec:
  serviceAccountName: tekton-serviceaccount
  taskRef:
    name: deploy-image
  inputs:
    resources:
      - name: image
        resourceRef:
          name: windfire-restaurants-node-image
    params:
      - name: deploy-args
        value:
          - new-app
          - '--docker-image'
          - $(inputs.resources.image.url)
      - name: route-expose-args
        value:
          - expose
          - svc/windfire-restaurants-node